version: '2'
services:
  fabio:
    build: "services/fabio"
    restart: always
    environment:
      HOST_IP: ${HOST_IP}
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes_from:
      - certificates

  web:
    build: "services/web"
    restart: always
    environment:
      # SERVICE_80_CHECK_HTTP: /
      # SERVICE_80_CHECK_INTERVAL: 15s
      # SERVICE_80_CHECK_TIMEOUT: 1s
      SERVICE_TAGS: http,urlprefix-/
    links:
      - nebula

  git:
    build: "services/git"
    restart: always
    environment:
      # SERVICE_80_CHECK_HTTP: /git
      # SERVICE_80_CHECK_INTERVAL: 15s
      # SERVICE_80_CHECK_TIMEOUT: 1s
      SERVICE_TAGS: http,urlprefix-/
    volumes:
      - "./services/git/root/etc/git/hooks:/etc/git/hooks"

  nebula:
    build: "services/nebula"
    command: "phoenix.server"
    restart: always
    expose:
      - "4000"
    links:
      - postgres
    environment:
      MIX_ENV: dev
      SERVICE_NAME: nebula
      SERVICE_TAGS: nebula
    volumes:
      - "./services/nebula:/container/app"
    volumes_from:
      - git

  postgres:
    build: "services/postgres"
    restart: always
    environment:
      PGDATA: /container/postgresql/data
      SERVICE_80_NAME: postgres
      SERVICE_TAGS: nebula
    volumes_from:
      - postgres_data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  certificates:
    image: gliderlabs/alpine:3.4
    command: "true"
    volumes:
      - "./conf/ssl/certificate.crt:/etc/ssl/certificate.crt:ro"
      - "./conf/ssl/certificate.key:/etc/ssl/certificate.key:ro"
      - "./conf/ssl/certificate.pem:/etc/ssl/certificate.pem:ro"

  postgres_data:
    image: gliderlabs/alpine:3.4
    command: "true"
    volumes:
      - "/container/postgresql/data"
