version: '2'
services:
  haproxy:
    build: "./services/haproxy"
    restart: always
    ports:
      - "5000:443"
      - "1936:1936"
    extra_hosts:
     - consul:172.20.10.10
    links:
      - web
      - git
    volumes_from:
      - certificates

  web:
    build: "./services/web"
    restart: always
    links:
      - nebula
    expose:
      - "80"
      - "443"
    volumes_from:
      - certificates

  git:
    build: "./services/git"
    restart: always
    expose:
      - "6000"
    volumes_from:
      - certificates

  nebula:
    build: "./services/nebula"
    command: "phoenix.server"
    restart: always
    expose:
      - "4000"
    links:
      - postgres
    extra_hosts:
     - nomad:172.20.10.10
     - consul:172.20.10.10
    environment:
      MIX_ENV: dev
    volumes:
      - ./services/nebula:/container/app
    volumes_from:
      - git

  postgres:
    build: "./services/postgres"
    restart: always
    environment:
      PGDATA: /container/postgresql/data
    volumes_from:
      - postgres_data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  certificates:
    image: gliderlabs/alpine:3.3
    command: "true"
    volumes:
      - ./conf/ssl/certificate.crt:/etc/ssl/certificate.crt:ro
      - ./conf/ssl/certificate.key:/etc/ssl/certificate.key:ro
      - ./conf/ssl/certificate.pem:/etc/ssl/certificate.pem:ro

  postgres_data:
    image: gliderlabs/alpine:3.3
    command: "true"
    volumes:
      - "/container/postgresql/data"
