#!/usr/bin/env bash
#
# Build image.

set -euo pipefail
IFS=$'\n\t'

main() {
  local tag;
  tag="$1"

  docker build --build-arg NOMAD_VERSION=${NOMAD_VERSION} --build-arg MIX_ENV={$MIX_ENV} --tag "${tag}" .
}

main "$1"
