env:
  RAILS_ENV: test
  RACK_ENV: test
  NODE_ENV: test

steps:

  # - wait

  # - name: ":package: Package"
  #   command: ".buildkite/steps/release.bash"
  #   timeout_in_minutes: 10
  #   env:
  #     MIX_ENV: prod
  #     NOMAD_VERSION: 0.4.0
  #   agents:
  #     docker: true
  #     capacity: low

  # - wait

  - block: ":rocket:"

  - name: ":googlecloud: Deploy"
    command: ".buildkite/steps/deploy.bash"
    timeout_in_minutes: 10
    agents:
      docker: true
      capacity: low
