env:
  REGISTRY_PATH: "gcr.io/nebula-1338"
  RAILS_ENV: test
  RACK_ENV: test
  NODE_ENV: test

steps:

  - wait

  - name: ":package: Package Release"
    command: ".buildkite/steps/release.bash"
    timeout_in_minutes: 5
    env:
      MIX_ENV: prod
      NOMAD_VERSION: 0.4.0
    agents:
      docker: true
      capacity: low

  - wait
