#!/usr/bin/env bash
#
# Requires socat and xquartz - `brew install xquartz socat`

set -euo pipefail
IFS=' '

readonly LOCAL_IP="$(ifconfig en0 | grep 'inet ' || ifconfig en1 | grep 'inet ' | cut -d " " -f2)"
xserver_pid=""

start_xserver() {
  echo "* starting local x server..."
  /opt/X11/bin/xquartz &
  xserver_pid="$!"
  sleep 5
  export DISPLAY=:0
  xhost "+${LOCAL_IP}"
}

start_container() {
  echo "* starting debug container..."
  docker-compose run \
    --rm \
    -e DISPLAY="${LOCAL_IP}:0" \
    nebula \
    iex --name debug@127.0.0.1 --hidden -e ":observer.start"
}

main() {
  start_xserver
  start_container
}

cleanup() {
  echo "* cleaning up..."
  if [[ "$xserver_pid" != "" ]]; then
    kill -9 "$xserver_pid"
  fi
}

trap cleanup EXIT
main
