#!/usr/bin/env bash

set -e

readonly TMPDIR="$(mktemp -d)"
readonly PRIVATE_IP="$(ifconfig en0 | grep 'inet ' | awk '{ print $2  }')"

handle_exit() {
  rm -rf "$TMPDIR"
}

main() {
  .dev/bin/consul agent \
    -dev \
    -log-level=INFO \
    -data-dir="$TMPDIR" \
    -bind="0.0.0.0" \
    -client="0.0.0.0" \
    -advertise="$PRIVATE_IP" \
    -ui-dir=.dev/consul/ui \
    -ui
}

trap handle_exit EXIT
main
