#!/usr/bin/env bash

set -e

readonly TMPDIR="$(mktemp -d)"
readonly PRIVATE_IP="$(ifconfig en1 | grep 'inet ' | awk '{ print $2  }')"

handle_exit() {
  rm -rf "$TMPDIR"
}

main() {
  docker run \
    --net=host \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:v7 \
    -internal -resync=10 -retry-attempts=10 "consul://$PRIVATE_IP:8500"
}

trap handle_exit EXIT
main
