#!/usr/bin/env bash

set -e

readonly TMPDIR="$(mktemp -d)"
readonly PRIVATE_IP="$(ifconfig en0 | grep 'inet ' | awk '{ print $2  }')"

handle_exit() {
  rm -rf "${TMPDIR}"
}

main() {
  .dev/bin/nomad agent \
    -dev \
    -bind="${PRIVATE_IP}" \
    -log-level=INFO \
    -config=.dev/nomad.json \
    -data-dir="${TMPDIR}"
}

trap handle_exit EXIT
main
