#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

main() {
  echo '--- Preparing...'
  pwd
  gcloud --quiet components update
  echo "$GCLOUD_SERVICE_KEY" | base64 --decode -i > "${HOME}/gcloud-service-key.json"
  gcloud auth activate-service-account --key-file "${HOME}/gcloud-service-key.json"
  gcloud config set project "$PROJECT_NAME"
}

main
