#!/usr/bin/with-contenv sh

exec /usr/local/bin/fabio \
  -registry.consul.addr="consul:8500" \
  -registry.consul.register.addr="consul:9998" \
  -ui.addr=":9998" \
  -cfg /etc/fabio/fabio.properties;
